server:
  port: 8082
  servlet:
    context-path: /leaderboard

leaderboard:
  isc-key: abcd

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leader_board
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: playerScoreGroup
      properties:
        spring:
          json:
            trusted:
              packages: '*'
        enable.auto.commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
    topic-player-score:
      name: playerScore

  redis:
    jedis:
      host-name: 127.0.0.1
      port: 6379
    maxNoOfRanks: 20
    key: leaderboard
